services:
  - type: cron
    name: forex-signals-bot
    schedule: "*/5 * * * *"
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 forex_signals.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: API_KEY
        sync: false
